[tool.poetry]
name = "board_to_fen"
version = "0.1.2"
description = "Convert chessboard images to FEN notation using a CNN model."
authors = ["Dominik Maćkiewicz <https://github.com/mcdominik>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
tensorflow = "2.17.1"
keras = "3.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
